source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'mbta-v2_Example', :exclusive => true do
  pod "mbta-v2", :path => "../"
end

target 'mbta-v2_Tests', :exclusive => true do
  pod "mbta-v2", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
